routes:
  index:
    url: /
    method: get
    action: index.controller:index

  auth.login:
    url: /login
    method: get
    action: auth.controller:login

  projects.index:
    url: /projects
    method: get
    action: projects.controller:index


  # Projects!

  # CookBook
  projects.cookbook.index:
    url: /projects/cookbook
    method: get
    action: projects.cookbook.controller:index

  # Boiler
  projects.boiler.index:
    url: /projects/private/boiler
    method: get
    action: projects.boiler.controller:index

  projects.boiler.download:
    url: /projects/private/boiler/download
    method: get
    action: projects.boiler.controller:download

  # Cluedo
  projects.humancluedo.index:
    url: /projects/private/humancluedo
    method: get
    action: projects.humancluedo.controller:index

  # Helius
  projects.helius.index:
    url: /projects/private/helius
    method: get
    action: projects.helius.controller:index



  # API
  api.index:
    url: /api/facebook
    method: get
    action: api.controller:facebook